<?php

use ExportBA\Entity\JobMetaData;
use ExportBA\Entity\JobMetaStatus;
use ExportBA\Entity\SimpleImportMetaDataProxy;
use ExportBA\Filter\JobId;
use SimpleImport\Entity\JobMetaData as SIData;

echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL;
$siExists = class_exists(SIData::class);
$siProxy = new class () { public function get($k, $v = null) { return $v; }};
?>
<HRBAXMLJobPositionPosting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Header>
    <SupplierId><?=$supplierId?></SupplierId>
    <Timestamp><?=date("Y-m-d\TH:i:s\Z")?></Timestamp>
    <Amount><?=count($jobs)?></Amount>
    <TypeOfLoad>D</TypeOfLoad>
  </Header>
  <Data>
    <?php $ItemsToDelete = [] ?>
<?php /** @var \Jobs\Entity\Job $job */ foreach ($jobs as $job):
    /** @var JobMetaData $meta */
    $meta = JobMetaData::fromJob($job);
    $extraData = $siExists ? SIData::fromJob($job) : $siProxy;?>
    <?php if ($job->isActive() && $meta->mustProcess()):
        if ($meta->isOffline()):
            $meta=$meta->withStatus(JobMetaData::STATUS_NEW, 'Reactiveated.');
          endif;?>
    <JobPositionPosting>
        <JobPositionPostingId><?=JobId::toAaId($job->getId(), $partnerNr)?></JobPositionPostingId>
        <HiringOrg>
            <HiringOrgName><![CDATA[<?php echo mb_substr($job->getOrganization()->getOrganizationName()->getName(),0, 90) ?>]]></HiringOrgName>
            <Industry>
                <NAICS>86.10.1</NAICS>
            </Industry>
            <Contact>
                <Salutation>1</Salutation>
                <FamilyName>Personalabteilung</FamilyName>
            </Contact>
    	</HiringOrg>

       <PostDetail>

       <?php if ($date = $extraData->get('StartDate')):?>
            <StartDate><?=$date?></StartDate>

       <?php elseif ($date = $job->getDatePublishStart()):?>
           <StartDate><?=$date->format('Y-m-d')?></StartDate>
        <?php endif?>
        <?php if ($date = $job->getDatePublishEnd()):?>
           <EndDate><?=$date->format('Y-m-d')?></EndDate>
        <?php endif?>
        <?php if ($date = $job->getDateModified()):?>
           <LastModificationDate><?=$date->format('c')?></LastModificationDate>
        <?php endif?>
           <Status>1</Status>
           <Action><?=$meta->isNew() ? 1 : 2?></Action>
           <SupplierId><?=$supplierId?></SupplierId>
           <SupplierName>stellenmarkt.de</SupplierName>
           <SupplierIndustrie>1</SupplierIndustrie>
<?php $link = 'https://stellenmarkt.com/de/job-' . $job->getId() . '.html';
    //if ($link = $job->getLink()): ?>
           <InternetReference><![CDATA[<?=mb_substr($link, 0, 200)?>]]></InternetReference>
<?php //endif; ?>

           <PostedBy>
                <Contact>
                    <Company><![CDATA[<?=mb_substr($job->getOrganization()->getOrganizationName()->getName(),0,90)?>]]></Company>
                    <JobContactWebSite><![CDATA[<?=$link ? mb_substr($link, 0, 200) : ''?>]]></JobContactWebSite>
                </Contact>
            </PostedBy>

        </PostDetail>
        <JobPositionInformation>
            <JobPositionTitle>
            <?php if ($title = $extraData->get('JobPositionTitle', [])['TitleCode']): ?>
                <TitleCode><?=$title?></TitleCode>
                <?php if ($degree = $extraData->get('JobPositionTitle')['Degree']): ?>
                <Degree><?=$degree?></Degree>
                <?php endif ?>
            <?php else: ?>

                <TitleCode><?=$this->titleCode($job->getTitle())?></TitleCode>
            <?php endif ?>
            </JobPositionTitle>
            <?php if ($altTitles = $extraData->get('AlternativeJobPositionTitle')): ?>

                <?php $altCount = 0; foreach ($altTitles as $alt): ?>

                    <?php if (isset($alt['TitleCode'])): ?>
                    <AlternativeJobPositionTitle>
                        <TitleCode><?= $alt['TitleCode']?></TitleCode>

                        <?php if (isset($alt['Degree'])): ?>
                        <Degree><?=$alt['Degree']?></Degree>
                        <?php endif ?>
                    </AlternativeJobPositionTitle>
                    <?php endif ?>
                    <?php if (++$altCount > 2): break; endif ?>

                <?php endforeach ?>

            <?php endif ?>

            <JobPositionTitleDescription><![CDATA[<?=
                $extraData->get('JobPositionTitleDescription') ?? mb_substr($job->getTitle(),0, 58)?>]]></JobPositionTitleDescription>
            <JobOfferType>1</JobOfferType>
            <SocialInsurance><?=$extraData->get('SocialInsurance') ?? 1?></SocialInsurance>

<?php if ($description = $job->getTemplateValues()->getHtml()):?>
            <Objective><![CDATA[<?=mb_substr($description, 0, 3995)?>]]></Objective>
<?php endif; ?>
            <EducationAuthorisation>1</EducationAuthorisation>
             <JobPositionDescription>
                 <?php $locationsCount = 0; if ($extraLocation = $extraData->get('Location')): ?>
                 <JobPositionLocation>
                    <Location>
                        <?php foreach (['CountryCode', 'Region', 'PostalCode', 'City' => 'Municipality'] as $name => $tag):
                            if (is_numeric($name)) { $name = $tag; }
                            if (!isset($extraLocation[$name]) || empty($extraLocation[$name])) { continue; }
                            echo "<$tag>" . $extraLocation[$name] . "</$tag>";
                        endforeach; $locationsCount++; ?>
                    </Location>
                 </JobPositionLocation>
                <?php else: $locations = $job->getLocations(); if (count($locations)):?>
                <JobPositionLocation>
                    <?php /** @var \Jobs\Entity\Location $location */ foreach ($locations as $i => $location):?>
                    <Location>
                        <CountryCode>DE</CountryCode>
                        <PostalCode><?php echo $location->getPostalCode() ?></PostalCode>
                        <Municipality><![CDATA[<?=substr($location->getCity(),0,35) ?>]]></Municipality>
                    </Location>
                    <?php $locationsCount++; endforeach?>
                </JobPositionLocation>
                 <?php else: $locationsCount++; ?>
                     <JobPositionLocation>
                         <Location><CountryCode>DE</CountryCode></Location>
                     </JobPositionLocation>
            <?php endif; endif; ?>
                <Application>
                    <KindOfApplication>6</KindOfApplication>
                </Application>
                <Classification>
                    <Schedule>
                        <WorkingPlan>1</WorkingPlan>
                    </Schedule>
                </Classification>
             </JobPositionDescription>
            <JobPositionRequirements>
                <QualificationsRequired>
                    <EducationQualifs>
                        <EduDegree>15</EduDegree>
                    </EducationQualifs>
                </QualificationsRequired>
            </JobPositionRequirements>
            <NumberToFill><?= $locationsCount ?: 1?></NumberToFill>
            <AssignmentStartDate><?=$extraData->get('AssignmentStartDate') ?? date('Y-m-d', time() + 24*60*60)?></AssignmentStartDate>
        </JobPositionInformation>
    </JobPositionPosting>
    <?php
          $meta->commit()->storeIn($job); $this->processed->count++;else:?>
    <?php if (!$meta->isNew() && !$meta->isOffline() && $meta->mustProcess()):
        $ItemsToDelete[] = JobId::toAaId($job->getId(), $partnerNr);
        $meta->withStatus(JobMetaData::STATUS_OFFLINE, 'Job is expired.')->commit()->storeIn($job);
        $this->processed->count++;
    endif;?>
    <?php endif; ?>

<?php endforeach; ?>
    <?php foreach ($ItemsToDelete as $item):?>
      <DeleteEntry>
        <EntryId><?=$item?></EntryId>
      </DeleteEntry>
    <?php endforeach; ?>
  </Data>
</HRBAXMLJobPositionPosting>
