<?php

use ExportBA\Entity\JobMetaData;
use ExportBA\Entity\JobMetaStatus;
use ExportBA\Entity\SimpleImportMetaDataProxy;
use ExportBA\Filter\JobId;
use SimpleImport\Entity\JobMetaData as SIData;

echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL; ?>
<HRBAXMLJobPositionPosting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Header>
    <SupplierId><?=$supplierId?></SupplierId>
    <Timestamp><?=date("Y-m-d\TH:i:s\Z")?></Timestamp>
    <Amount><?=count($jobs)?></Amount>
    <TypeOfLoad>D</TypeOfLoad>
  </Header>
  <Data>
    <?php $ItemsToDelete = [] ?>
<?php /** @var \Jobs\Entity\Job $job */ foreach ($jobs as $job):
    /** @var JobMetaData $meta */
    $meta = $job->getAttachedEntity(JobMetaData::class);
    if (!$meta) {
        $meta = $job->createAttachedEntity(JobMetaData::class, ['jobId' => $job->getId(), 'status' => 'new']);
    }
    $extraData = (new SimpleImportMetaDataProxy($job))->getData();?>
    <?php if ($job->isActive() && $meta->mustProcess()):?>
    <JobPositionPosting>
        <JobPositionPostingId><?=JobId::toAaId($job->getId(), $partnerNr)?></JobPositionPostingId>
        <HiringOrg>
            <HiringOrgName><![CDATA[<?php echo mb_substr($job->getOrganization()->getOrganizationName()->getName(),0, 90) ?>]]></HiringOrgName>
            <Industry>
                <NAICS>86.10.1</NAICS>
            </Industry>
            <Contact>
                <Salutation>1</Salutation>
                <FamilyName>Personalabteilung</FamilyName>
            </Contact>
    	</HiringOrg>

       <PostDetail>

       <?php if ($date = $extraData['StartDate'] ?? null):?>
            <StartDate><?=$extraData['StartDate']?></StartDate>

       <?php elseif ($date = $job->getDatePublishStart()):?>
           <StartDate><?=$date->format('Y-m-d')?></StartDate>
        <?php endif?>
        <?php if ($date = $job->getDatePublishEnd()):?>
           <EndDate><?=$date->format('Y-m-d')?></EndDate>
        <?php endif?>
        <?php if ($date = $job->getDateModified()):?>
           <LastModificationDate><?=$date->format('c')?></LastModificationDate>
        <?php endif?>
           <Status>1</Status>
           <Action><?=2 //$meta->isOnline() ? 2 : 1?></Action>
           <SupplierId><?=$supplierId?></SupplierId>
           <SupplierName>stellenmarkt.de</SupplierName>
           <SupplierIndustrie>1</SupplierIndustrie>
<?php $link = 'https://stellenmarkt.com/de/job-' . $job->getId() . '.html';
    //if ($link = $job->getLink()): ?>
           <InternetReference><![CDATA[<?=mb_substr($link, 0, 200)?>]]></InternetReference>
<?php //endif; ?>

           <PostedBy>
                <Contact>
                    <Company><![CDATA[<?=mb_substr($job->getOrganization()->getOrganizationName()->getName(),0,90)?>]]></Company>
                    <JobContactWebSite><![CDATA[<?=$link ? mb_substr($link, 0, 200) : ''?>]]></JobContactWebSite>
                </Contact>
            </PostedBy>

        </PostDetail>
        <JobPositionInformation>
            <JobPositionTitle>
            <?php if (isset($extraData['JobPositionTitle']['TitleCode'])): ?>
                <TitleCode><?=$extraData['JobPositionTitle']['TitleCode']?></TitleCode>
                <?php if (isset($extraData['JobPositionTitle']['Degree'])): ?>
                <Degree><?=$extraData['JobPositionTitle']['Degree']?></Degree>
                <?php endif ?>
            <?php else: ?>

                <TitleCode><?=$this->titleCode($job->getTitle())?></TitleCode>
            <?php endif ?>
            </JobPositionTitle>
            <?php if (isset($extraData['AlternativeJobPositionTitle'])): ?>
            <AlternativeJobPositionTitle>
                <?php $altCount = 0; foreach ($extraData['AlternativeJobPositionTitle'] as $alt): ?>
                    <?php if (isset($alt['TitleCode'])): ?>
                    <TitleCode><?= $alt['TitleCode']?></TitleCode>
                    <?php endif ?>
                    <?php if (isset($alt['Degree'])): ?>
                    <Degree><?=$alt['Degree']?></Degree>
                    <?php endif ?>
                    <?php if (++$altCount > 2): break; endif ?>
                <?php endforeach ?>
            </AlternativeJobPositionTitle>
            <?php endif ?>

            <JobPositionTitleDescription><![CDATA[<?=
                $extraData['JobPositionTitleDescription'] ?? mb_substr($job->getTitle(),0, 58)?>]]></JobPositionTitleDescription>
            <JobOfferType>1</JobOfferType>
            <SocialInsurance><?=$extraData['SocialInsurance'] ?? 1?></SocialInsurance>

<?php if ($description = $job->getTemplateValues()->getHtml()):?>
            <Objective><![CDATA[<?=mb_substr($description, 0, 3995)?>]]></Objective>
<?php endif; ?>
            <EducationAuthorisation>1</EducationAuthorisation>
             <JobPositionDescription>
                 <?php if (isset($extraData['Location'])): ?>
                 <JobPositionLocation>
                    <Location>
                        <?php foreach (['CountryCode', 'Region', 'PostalCode', 'City' => 'Municipality'] as $name => $tag):
                            if (is_numeric($name)) { $name = $tag; }
                            if (!isset($extraData['Location'][$name])) { continue; }
                            echo "<$tag>" . $extraData['Location'][$name] . "</$tag>";
                        endforeach ?>
                    </Location>
                 </JobPositionLocation>
                <?php else: $locations = $job->getLocations(); if (count($locations)):?>
                <JobPositionLocation>
                    <?php /** @var \Jobs\Entity\Location $location */ foreach ($locations as $i => $location):?>
                    <Location>
                        <CountryCode>DE</CountryCode>
                        <PostalCode><?php echo $location->getPostalCode() ?></PostalCode>
                        <Municipality><![CDATA[<?=substr($location->getCity(),0,35) ?>]]></Municipality>
                    </Location>
                    <?php endforeach?>
                </JobPositionLocation>
                 <?php else: ?>
                     <JobPositionLocation>
                         <Location><CountryCode>DE</CountryCode></Location>
                     </JobPositionLocation>
            <?php endif; endif; ?>
                <Application>
                    <KindOfApplication>6</KindOfApplication>
                </Application>
                <Classification>
                    <Schedule>
                        <WorkingPlan>1</WorkingPlan>
                    </Schedule>
                </Classification>
             </JobPositionDescription>
            <JobPositionRequirements>
                <QualificationsRequired>
                    <EducationQualifs>
                        <EduDegree>15</EduDegree>
                    </EducationQualifs>
                </QualificationsRequired>
            </JobPositionRequirements>
            <NumberToFill><?= count($locations)?></NumberToFill>
            <AssignmentStartDate><?=$extraData['AssignmentStartDate'] ?? date('Y-m-d', time() + 24*60*60)?></AssignmentStartDate>
        </JobPositionInformation>
    </JobPositionPosting>
    <?php $meta->commit(); $this->processed->count++;else:?>
    <?php if (!$meta->hasStatus('new') && !$meta->hasStatus(JobMetaStatus::OFFLINE) && $meta->mustProcess()):
        $ItemsToDelete[] = $partnerNr . '-' . $job->getId() . '-S';
        $meta->updateStatus(JobMetaStatus::OFFLINE, 'Job is expired.')->commit();
        $this->processed->count++;
    endif;?>
    <?php endif; ?>

<?php endforeach; ?>
    <?php foreach ($ItemsToDelete as $item):?>
      <DeleteEntry>
        <EntryId><?=$item?></EntryId>
      </DeleteEntry>
    <?php endforeach; ?>
  </Data>
</HRBAXMLJobPositionPosting>
